# For Atom Feed
domain: www.organicelement.com
author: Organic Element LLC
email: chris.custine@organicelement.com
title: Organic Element

# standard jekyll configuration

#source: porto

#permalink: /blog/:year/:month/:day/:title
permalink: /blog/articles/:title
highlighter: pygments
#highlighter: rouge
exclude:
- master
- php
- organicelement.github.io.iml

#include:
#- blog
#- _javascript

markdown: kramdown

# Custom site configuration
#lang: en

sass:
#    sass_dir: master/sass
    style: :compressed
    load_paths:
    - "master/sass"
    - "custom/sass"

paginate: 1
paginate_path: "/blog/page:num"

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"